# Generated by Django 5.1.2 on 2025-02-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=10),
        ),
    ]
