# Generated by Django 5.1.2 on 2025-02-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'Select a country'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('BR', 'Brazil'), ('JP', 'Japan'), ('CN', 'China'), ('IN', 'India')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'Select a country'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('BR', 'Brazil'), ('JP', 'Japan'), ('CN', 'China'), ('IN', 'India')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('employer', 'Employer')], max_length=10),
        ),
    ]
