# Generated by Django 5.1.2 on 2025-03-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('employer', 'Employer')], max_length=10),
        ),
    ]
