# Generated by Django 5.1.2 on 2025-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.TextField(default=''),
        ),
    ]
