# Generated by Django 5.1.2 on 2025-03-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('admin', 'Admin'), ('employee', 'Employee')], max_length=10),
        ),
    ]
