# Generated by Django 5.1.2 on 2025-03-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'Select a country'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('BR', 'Brazil'), ('JP', 'Japan'), ('CN', 'China'), ('IN', 'India')], max_length=100),
        ),
    ]
