# Generated by Django 5.1.2 on 2025-02-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_user_type'),
        ('app', '0007_alter_user_user_type'),
    ]

    operations = [
    ]
