# Generated by Django 5.1.2 on 2025-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('employee', 'Employee')], max_length=10),
        ),
    ]
