# Generated by Django 5.1.2 on 2025-02-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_user_type'),
        ('app', '0012_alter_job_created_by_alter_user_user_type'),
        ('app', '0013_alter_user_user_type'),
    ]

    operations = [
    ]
