# Generated by Django 5.1.2 on 2025-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20250217_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('employee', 'Employee')], max_length=10),
        ),
    ]
