# Generated by Django 5.1.2 on 2025-03-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_jobapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='portfolio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
