# Generated by Django 5.1.2 on 2025-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=10),
        ),
    ]
