# Generated by Django 5.1.2 on 2025-03-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_jobapplication_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('admin', 'Admin'), ('employee', 'Employee')], max_length=10),
        ),
    ]
