COUNTRIES = [
        ('', 'Select a country'),
        ('US', 'United States'),
        ('UK', 'United Kingdom'),
        ('CA', 'Canada'),
        ('AU', 'Australia'),
        ('FR', 'France'),
        ('DE', 'Germany'),
        ('IT', 'Italy'),
        ('ES', 'Spain'),
        ('PT', 'Portugal'),
        ('BR', 'Brazil'),
        ('JP', 'Japan'),
        ('CN', 'China'),
        ('IN', 'India'),
    ]
